#!/usr/bin/env bash
#
# Generate GitHub Actions workflow files for each PHP version and platform
#
# Usage: ./scripts/generate-workflows.sh
#
# This script fetches supported PHP versions from php.watch API and generates
# individual workflow files for each version + platform combination.
#

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
WORKFLOWS_DIR="${PROJECT_ROOT}/.github/workflows"

# Platform configurations (platform:runner pairs)
PLATFORMS="darwin-arm64:macos-14 darwin-amd64:macos-13"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[OK]${NC} $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# Fetch supported PHP versions from php.watch API
fetch_php_versions() {
    local versions
    versions=$(curl -fsSL "https://php.watch/api/v1/versions/secure" 2>/dev/null | \
        jq -r '.data | to_entries[] | .value.name' | \
        sort -V)

    if [[ -z "$versions" ]]; then
        log_error "Failed to fetch PHP versions"
        exit 1
    fi

    echo "$versions"
}

# Generate workflow file for a specific PHP version and platform
generate_workflow() {
    local php_minor="$1"
    local platform="$2"
    local runner="$3"

    local platform_short="${platform#darwin-}"  # arm64 or amd64
    local workflow_file="${WORKFLOWS_DIR}/php-${php_minor}-${platform_short}.yml"

    log_info "Generating: php-${php_minor}-${platform_short}.yml"

    cat > "$workflow_file" << EOF
# Auto-generated by scripts/generate-workflows.sh
# Do not edit manually - changes will be overwritten
name: PHP ${php_minor} (${platform_short})

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3:00 UTC
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if version unchanged'
        type: boolean
        default: false
      force_rebuild_deps:
        description: 'Force rebuild dependencies'
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-php.yml
    with:
      php_minor: "${php_minor}"
      platform: "${platform}"
      runner: "${runner}"
      force_build: \${{ inputs.force_build || false }}
      force_rebuild_deps: \${{ inputs.force_rebuild_deps || false }}
    secrets: inherit
EOF
}

# Clean up old workflow files
cleanup_old_workflows() {
    log_info "Cleaning up old per-version workflow files..."

    # Remove old php-X.Y-*.yml files (but not _build-*.yml or generate-*.yml)
    find "$WORKFLOWS_DIR" -name 'php-*.yml' -type f -delete 2>/dev/null || true
}

# Main
main() {
    echo ""
    echo "========================================"
    echo "  PHM Workflow Generator"
    echo "========================================"
    echo ""

    # Fetch versions
    local versions
    versions=$(fetch_php_versions)

    echo "Supported PHP versions:"
    echo "$versions" | sed 's/^/  - /'
    echo ""

    # Clean old files
    cleanup_old_workflows

    # Generate workflow for each version + platform
    local count=0
    while read -r php_minor; do
        [[ -z "$php_minor" ]] && continue

        for entry in $PLATFORMS; do
            local platform="${entry%%:*}"
            local runner="${entry##*:}"
            generate_workflow "$php_minor" "$platform" "$runner"
            ((count++))
        done
    done <<< "$versions"

    echo ""
    log_success "Generated $count workflow files"
    echo ""

    # List generated files
    echo "Generated workflows:"
    ls -1 "${WORKFLOWS_DIR}"/php-*.yml 2>/dev/null | sed 's|.*/||' | sed 's/^/  /'
}

main "$@"
